-- =========================================
-- College ERP Management System
-- Database Schema for PostgreSQL
-- =========================================

-- Drop existing tables & triggers in correct dependency order
DROP TABLE IF EXISTS staff_attendance CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

-- Drop function if exists
DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;

-- Function for automatically updating updated_at timestamp on record modification
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =========================================
-- 1. DEPARTMENTS
-- =========================================

CREATE TABLE departments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_departments_updated_at
BEFORE UPDATE ON departments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- =========================================
-- 2. COURSES
-- =========================================

CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(255) NOT NULL,
    department_id INTEGER NOT NULL
        REFERENCES departments(id)
        ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_course_per_department
        UNIQUE (course_name, department_id)
);

CREATE TRIGGER update_courses_updated_at
BEFORE UPDATE ON courses
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- =========================================
-- 3. STUDENTS
-- =========================================

CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    course_id INTEGER NOT NULL
        REFERENCES courses(id)
        ON DELETE RESTRICT,
    city VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- =========================================
-- 4. USERS (STAFF / EMPLOYEES)
-- =========================================

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,

    role VARCHAR(50) NOT NULL
        CHECK (
            role IN (
                'principal',
                'hod',
                'teacher',
                'admission_staff'
            )
        ),

    department_id INTEGER
        REFERENCES departments(id)
        ON DELETE SET NULL,

    designation VARCHAR(255),
    phone VARCHAR(20),

    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive')),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- =========================================
-- 5. STAFF ATTENDANCE
-- =========================================

CREATE TABLE staff_attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,
    attendance_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('present', 'absent')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_user_attendance_date
        UNIQUE (user_id, attendance_date)
);

CREATE TRIGGER update_staff_attendance_updated_at
BEFORE UPDATE ON staff_attendance
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();


-- =========================================
-- INDEXES FOR OPTIMAL QUERY PERFORMANCE
-- =========================================

CREATE INDEX idx_students_course_id ON students(course_id);
CREATE INDEX idx_students_city ON students(city);
CREATE INDEX idx_courses_department_id ON courses(department_id);
CREATE INDEX idx_users_department_id ON users(department_id);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_status ON users(status);
CREATE INDEX idx_staff_attendance_user_id ON staff_attendance(user_id);
CREATE INDEX idx_staff_attendance_date ON staff_attendance(attendance_date);
CREATE INDEX idx_staff_attendance_status ON staff_attendance(status);